name: Sync from GitLab

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone GitLab repository (mirror)
        run: |
          git clone --mirror https://gitlab.villejuif.fr/J-COQBLIN/convert2ebook.git repo

      - name: Push to GitHub (mirror)
        run: |
          cd repo
          git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --mirror
